FROM debian:bookworm-slim
FROM php:7.4-fpm-buster
LABEL maintainer="Alfonso Alvar"

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Copiar el archivo de configuración personalizado
COPY php-7.4.ini /usr/local/etc/php/conf.d/custom.ini

WORKDIR /var/www/html
