FROM php:8.5-fpm-bookworm

LABEL maintainer="Alfonso Alvar"

# Instalación de dependencias
RUN apt-get update && apt-get install -y --allow-unauthenticated \
    git \
    unzip \
    zip \
    libzip-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql mysqli zip

# Añadir Composer
COPY --from=composer:2.2 /usr/bin/composer /usr/bin/composer

# Copiar el archivo de configuración personalizado
COPY php-8.5.ini /usr/local/etc/php/conf.d/custom.ini  
WORKDIR /var/www/html