# Usaremos php:8.4-fpm-bookworm. La imagen oficial de PHP ya está basada en Debian.
FROM php:8.4-fpm-bookworm
LABEL maintainer="Tu Nombre"

# Instalar extensiones necesarias (mysqli y otras comunes)
RUN docker-php-ext-install pdo pdo_mysql mysqli
# Copiar el archivo de configuración personalizado
COPY php-8.4.ini /usr/local/etc/php/conf.d/custom.ini

WORKDIR /var/www/html