FROM httpd:2.4.59-bookworm
LABEL maintainer="Alfonso Alvar"

# Eliminar configuración de sitio por defecto
RUN rm /usr/local/apache2/conf/httpd.conf

# Copiar archivo de configuración principal (para incluir vhosts)
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
